/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "chAx_aliases.h"
#include "chAx.h"
#include "chBx_aliases.h"
#include "chBx.h"
#include "isrXP.h"
#include "isrXL.h"
#include "chAy_aliases.h"
#include "chAy.h"
#include "chBy_aliases.h"
#include "chBy.h"
#include "isrYP.h"
#include "isrYL.h"
#include "UART.h"
#include "isrRx.h"
#include "PwmY_aliases.h"
#include "PwmY.h"
#include "PwmX_aliases.h"
#include "PwmX.h"
#include "Clock_1.h"
#include "PWM.h"
#include "ResetPWM_aliases.h"
#include "ResetPWM.h"
#include "Reset_Pin_aliases.h"
#include "Reset_Pin.h"
#include "A1_aliases.h"
#include "A1.h"
#include "B1_aliases.h"
#include "B1.h"
#include "A2_aliases.h"
#include "A2.h"
#include "B2_aliases.h"
#include "B2.h"
#include "SenX_aliases.h"
#include "SenX.h"
#include "SenY_aliases.h"
#include "SenY.h"
#include "isrX.h"
#include "isrY.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

